### ISSUE TITLE
Is this right?

### ISSUE THREAD

**Issue by karaloka** [CorvusCodex/Multithread-Bitcoin-Brute-Force#2]
Hello
You wrote: "The script will display the loop count for each worker process in real-time".
This is what I'm seeing:
![bitcoin_w_c_2](https://github.com/CorvusCodex/Multithread-Bitcoin-Brute-Force/assets/93810574/22627b21-693e-48db-b126-6114c41a9819)
The image is static. Nothing moves.
In Task Manager, I can see this:
![bitcoin_w_c_1](https://github.com/CorvusCodex/Multithread-Bitcoin-Brute-Force/assets/93810574/8f09a263-a27c-4796-b42c-23f33ce66929)
Is this right? Is it working?
Thank you for your script.

**Comment by CorvusCodex** [comment]
@karaloka yeah it works fine for me. 
![Capture](https://github.com/CorvusCodex/Multithread-Bitcoin-Brute-Force/assets/56726555/3f43326d-1ce7-438e-9989-45c0b9f2d0b1)
What exact nodejs version you are using? What exact OS and OS version you are using? Thanks for feedback!

**Comment by karaloka** [comment]
Hi
I'm using Node v18.16.1 x64. 
My OS:
Edition:	Windows 11 Home
Version:	22H2 (22621.1848)
Intel(R) Core(TM) i5-9600K CPU @ 3.70GHz
RAM: 32,0 GB

I ran and stopped the script several times. There are no error messages, but the data for the loop count never appears. The Task Manager shows that the script is consuming resources. Maybe it's just a display issue. Well, I'm not sure.
Thanks man.

**Comment by karaloka** [comment]
Sorry, I didn't mean to close this session.

**Comment by CorvusCodex** [comment]
@karaloka 
Install latest nodejs 20
then type npm update -g in command prompt
then navigate to project folder and type npm update and then node app.js. Tell me if issue is fixed. Try running command prompt as admin if nothing works too

**Comment by CorvusCodex** [comment]
Good job! :D @karaloka you are amazing!
I will fix this to be more responsive.

**Comment by CorvusCodex** [comment]
@karaloka i have implemented fix. Can you test it?

**Comment by CorvusCodex** [comment]
I have implemented new fix.
